version: '2'
services:
  nginx:
    container_name: zhacker-nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
#    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anywhere

  redis:
    image: redis
    container_name: redisdb
    ports:
      - "6379:6379"

  zhacker-gateway-1:
    container_name: zhacker-gateway-1
    build: .
    restart: always
    depends_on:
      - mysqldb
      - redisdb
      - zhacker-nginx

  zhacker-gateway-2:
    container_name: zhacker-gateway-2
    build: .
    restart: always
    depends_on:
      - mysqldb
      - redisdb
      - zhacker-nginx