spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:/tmp/passportdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    continue-on-error: false
    initialization-mode: always
    initialize: true
    data: classpath:data.sql
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: hash_map
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: D:/log/
#  file: D:/log/logback.log
#  level: debug
merryyou:
  security:
    code:
      image:
        width: 90
        height: 20
        length: 4
        expireIn: 30
        url: /code/*
    session:
      maximumSessions: 1
      maxSessionsPreventsLogin: false
#      sessionInvalidUrl : /merryyou-session-invalid.html
    loginType: JSON