server.port: 14000

#security.user.password: password
logging.level.org.springframework.security: DEBUG

spring:
  application:
    name: zhacker-gateway-route
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:/tmp/gatewaydb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    continue-on-error: false
    initialize: true

security:
  user:
    password: none
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

management.security.enabled: false

#zuul:
#  ignored-services: '*'
#  routes:
#    zhacker-dubbo-invoker:
#      path: /dubbo/**
#      strip-prefix: false
#    retail-sku:
#      path: /sku/**
#    retail-stock:
#      path: /stock/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul.groovy.path: /tmp/groovy-filter/


#spring.datasource.url: jdbc:mysql://127.0.0.1:3306/gateway?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
#spring.datasource.username: root
#spring.datasource.password: anywhere
